server:
  port: 9080
  
spring:
  application:
    name: INVENTORYMVC
 
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: postgres
    password: postgres
 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka